import Content from '@/components/roadmap/Content'
import React from 'react'

export const metadata = {
  title: "Econox Coin - Roadmap",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

const page = () => {
  return (
    <Content />
  )
}

export default page